package top.bogey.touch_tool.bean.action;

public enum ActionType {
    // 开始
    MANUAL_START,
    APPLICATION_START,
    TIME_START,
    NOTIFICATION_START,
    NETWORK_START,
    BATTERY_START,
    SCREEN_START,
    BLUETOOTH_START,
    OUT_CALL_START,
    INNER_START,

    // 逻辑
    IF_LOGIC,
    WAIT_IF_LOGIC,
    SWITCH_LOGIC,
    CHOICE_LOGIC,
    FOR_LOGIC,
    WHILE_LOGIC,
    SEQUENCE_LOGIC,
    RANDOM_LOGIC,
    PARALLEL_LOGIC,

    // 通用任务
    DELAY,
    LOG,
    STICK,
    CLOSE_STICK,
    CLOSE_ALL_STICK,
    
    EXECUTE_TASK,
    
    CLICK_POSITION,
    CLICK_NODE,
    TOUCH,
    EDITTEXT_INPUT,

    SAVE,
    LOAD,


    // 系统动作
    OPEN_APP,
    OPEN_URI_SCHEME,
    SHARE_TO,

    PLAY_RINGTONE,
    STOP_RINGTONE,
    TEXT_TO_SPEECH,

    SHELL,

    WRITE_TO_CLIPBOARD,

    SWITCH_SCREEN,
    GET_SCREEN_STATUS,

    SWITCH_CAPTURE,
    CHECK_CAPTURE_READY,

    GET_CURRENT_APPLICATION,
    CHECK_IN_APPLICATION,

    GET_BATTERY_STATUS,

    GET_NETWORK_STATUS,

    GET_CURRENT_DATE,
    GET_CURRENT_TIME,

    // 文本获取与检测
    STRING_FROM_OBJECT,
    STRING_TO_NUMBER,
    STRING_APPEND,
    STRING_REGEX,
    STRING_SPLIT,
    STRING_EQUAL,
    STRING_REPLACE,
    GET_OCR_TEXT,


    GET_NODE_BY_TEXT,
    GET_NODES_BY_TEXT,
    GET_AREA_BY_OCR_TEXT,

    // 数值
    NUMBER_ADD,
    NUMBER_SUB,
    NUMBER_MUL,
    NUMBER_DIV,
    NUMBER_MOD,
    NUMBER_EQUAL,
    NUMBER_LESS,
    NUMBER_GREATER,
    NUMBER_RANDOM,
    NUMBER_TO_INT,

    CHECK_NUMBER_IN_VALUE_AREA,
    NUMBER_TO_VALUE_AREA,

    MATH_EXPRESSION,

    // 图片
    GET_IMAGE,
    GET_IMAGE_IN_AREA,
    SAVE_IMAGE,
    GET_AREA_BY_IMAGE,
    GET_AREAS_BY_IMAGE,
    GET_AREA_IN_IMAGE,
    
    // 控件
    GET_NODE,
    GET_NODES,
    GET_NODE_INFO,
    GET_NODE_CHILDREN,
    GET_NODE_PARENT,
    GET_NODES_IN_POSITION,
    GET_WINDOWS,
    CHECK_NODE_VALID,
    
    // 颜色
    GET_COLOR_IN_POSITION,
    GET_COLOR_AREA,
    GET_COLOR_AREAS,
    COLOR_EQUAL,
    
    // 条件
    BOOLEAN_OR,
    BOOLEAN_AND,
    BOOLEAN_NOT,

    // 区域
    AREA_TO_INT,
    AREA_FROM_INT,
    CHECK_AREA_CONTAIN_POS,
    CHECK_AREA_RELATION,
    GET_AREA_INTERSECTION,
    GET_AREA_CENTER,
    PICK_AREA,

    // 位置
    POSITION_FROM_INT,
    POSITION_TO_INT,
    POS_OFFSET,
    POS_TO_TOUCH,

    // 数组
    LIST_SET,
    LIST_MAKE,
    LIST_GET,
    LIST_ADD,
    LIST_REMOVE,
    LIST_CLEAR,
    LIST_SIZE,
    LIST_INDEX_OF,
    CHECK_LIST_INDEX_VALID,
    LIST_APPEND,
    LIST_FOREACH,

    // 字典
    MAP_SET,
    MAP_MAKE,
    MAP_GET,
    MAP_ADD,
    MAP_REMOVE,
    MAP_CLEAR,
    MAP_SIZE,
    MAP_KEYS,
    MAP_VALUES,
    MAP_APPEND,
    MAP_FOREACH,

    // 变量
    VAR_SET,
    VAR_GET,
}
